[PROTOCOLS]
B-Cell Epitope Prediction = [
    {"tag": "section", "text": "Antigenicity Prediction", "icon": "bookmark.png", "children": [
        {"tag": "protocol", "value": "ProtBCellEpitopeBepiPredPredict", "text": "default"},
        {"tag": "protocol", "value": "ProtBCellEpitopeEpiDopePredict", "text": "default"},
        {"tag": "protocol", "value": "ProtBCellEpitopeConsensus", "text": "default"},
        {"tag": "protocol", "value": "ProtBCellEpitopeBlastFilter", "text": "default"},
        {"tag": "protocol", "value": "ProtBCellEpitopeNetMHCIIpan", "text": "default"}
    ]}
]
